server:
  port: 8767
spring:
  application:
    name: oauth-authentication-service
  redis:
   host: 127.0.0.1
  port: 6379
  pool:
    max-idle: 100
    min-idle: 1
    max-active: 1000
    max-wait: -1
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/